### ISSUE TITLE
Remove periodic key from SOAP

### ISSUE THREAD

**Issue by PythonFZ** [zincware/IPSuite#111]
As mentioned in #104 the SOAP parameters currently contain the periodic key. This should not be a parameter but defined by the data.

```yaml
ConfigurationSelection_1_kernel:
    soap:
        _type: soap_parameter_dataclass
        value:
            l_max: 7
            n_jobs: -1
            n_max: 7
            periodic: true
            r_cut: 9.0
            rbf: gto
            sigma: 1.0
            weighting: null
```
